export const Users = [
  {
    id:1,
    profilePicture: "logo2",
    username: "Bhama",
  },
  {
    id:2,
    profilePicture: "logo1",
    username: "sophie",
  },
  {
    id:3,
    profilePicture: "logo1",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "logo1",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "logo1",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "logo1",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "logo1",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "logo1",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "logo1",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "logo1",
    username: "Safak Kocaoglu",
  },
];

export const Datas = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "home1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "home2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "home3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "home2.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "home2.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "home2.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "home2.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "home2.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "home2.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "home2.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];